### ISSUE TITLE
Exception in thread Thread-1

### ISSUE THREAD

**Issue by 828768** [maxzh0916/Shadowsowcks1Click#3]
装完了不能启动，大神遇到过么，搬瓦工的一个openvz的vps，其他地方买的同样的openvz的vps没这问题
```
[root@xxx shadowsocksr]# ./server.py 
IPv6 support
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "./server.py", line 39, in run
    self.obj.thread_db(self.obj)
  File "/root/shadowsocksr/db_transfer.py", line 233, in thread_db
    ServerPool.get_instance()
  File "/root/shadowsocksr/server_pool.py", line 69, in get_instance
    ServerPool.instance = ServerPool()
  File "/root/shadowsocksr/server_pool.py", line 49, in __init__
    self.config = shell.get_config(False)
  File "/root/shadowsocksr/shadowsocks/shell.py", line 299, in get_config
    check_config(config, is_local)
  File "/root/shadowsocksr/shadowsocks/shell.py", line 129, in check_config
    encrypt.try_cipher(config['password'], config['method'])
  File "/root/shadowsocksr/shadowsocks/encrypt.py", line 46, in try_cipher
    Encryptor(key, method)
  File "/root/shadowsocksr/shadowsocks/encrypt.py", line 90, in __init__
    random_string(self._method_info[1]))
  File "/root/shadowsocksr/shadowsocks/encrypt.py", line 119, in get_cipher
    return m[2](method, key, iv, op)
  File "/root/shadowsocksr/shadowsocks/crypto/sodium.py", line 71, in __init__
    load_libsodium()
  File "/root/shadowsocksr/shadowsocks/crypto/sodium.py", line 40, in load_libsodium
    'libsodium')
  File "/root/shadowsocksr/shadowsocks/crypto/util.py", line 83, in find_library
    lib = CDLL(path)
  File "/usr/lib/python2.6/ctypes/__init__.py", line 353, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libsodium.so.23: cannot open shared object file: No such file or directory
```

**Comment by 828768** [comment]
是`libsodium` 没安装，导致协议启动失败，[SSR后端节点提示错误无法启动解决方法](https://sobaigu.com/ssrnode-start-with-error-exception.html)
